
apiVersion: v1

kind: Secret
metadata:
  name: postgres-secret

data:
  POSTGRES_PASSWORD: cm9vdA==




# El formato que creo el oneliner para crear la variable de ambiente
#apiVersion: v1
#data:
#  POSTGRES_PASSWORD: cm9vdA==
#kind: Secret
#metadata:
#  creationTimestamp: null
#  name: postgres-secret
