apiVersion: v1
kind: Service
metadata:
  labels:
    app: interns-db-app
  name: interns-db-service
spec:
  selector:
    app: interns-db-app
  ports:
    - 
      protocol: TCP
      port: 5432
      targetPort: 5432
